name: Build and Test (Java)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - 'pkg/java/**'
      - 'OpenFGAParser.g4'
      - 'OpenFGALexer.g4'
      - tests/**'

permissions:
  contents: read

jobs:
  lint:
    name: Lint Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: 20
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: | 
            ./pkg/java/*.gradle*
            ./pkg/java/**/gradle-wrapper.properties
      - name: Lint Java source
        run: make lint-java

  test:
    name: Test Java
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '11', '17', '20' ]

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: | 
            ./pkg/java/*.gradle*
            ./pkg/java/**/gradle-wrapper.properties
      - name: Test and Build with Gradle
        run: make test-java
