name: Build and Test (Go)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/148-support-modular-models
    tags:
      - 'v*'
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - 'pkg/go/**'
      - 'OpenFGAParser.g4'
      - 'OpenFGALexer.g4'
      - 'tests/**'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: '>=1.22.2'
          cache-dependency-path: './pkg/go/go.sum'
          check-latest: true

      - name: Audit dependencies
        run: make audit-go

      - name: Lint
        run: make lint-go

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22']
    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: ${{ matrix.go-version }}
        cache-dependency-path: './pkg/go/go.sum'
        check-latest: true

    - name: Build
      run: make test-go

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    permissions:
      contents: write
      packages: write # publish a new github release
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0

      - uses: Roang-zero1/github-create-release-action@57eb9bdce7a964e48788b9e78b5ac766cb684803
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
