name: Build and Test (JS)

on:
  workflow_dispatch:
  merge_group:
    paths:
      - 'pkg/js/**'
  pull_request:
    paths:
      - 'pkg/js/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2.9.1

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@openfga'
          always-auth: false
          cache: 'npm'
          cache-dependency-path: ./pkg/js/package-lock.json

      - name: Build
        run: make all-tests-js