name: Build and Test (JS)

on:
  workflow_dispatch:
  merge_group:
    paths:
      - 'pkg/js/**'
      - 'OpenFGAParser.g4'
      - 'OpenFGALexer.g4'
  pull_request:
    paths:
      - 'pkg/js/**'
      - 'OpenFGAParser.g4'
      - 'OpenFGALexer.g4'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Set up node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./pkg/js/package-lock.json  
      
      - name: Audit dependencies
        run: make audit-js

      - name: Run Prettier
        run: make format-js

      - name: Run eslint
        run: make lint-js

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@openfga'
          always-auth: false
          cache: 'npm'
          cache-dependency-path: ./pkg/js/package-lock.json  

      - name: Build
        run: make all-tests-js