name: Build and Test (Go)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  merge_group:
    paths:
      - 'pkg/go/**'
      - 'OpenFGAParser.g4'
      - 'OpenFGALexer.g4'
  pull_request:
    paths:
      - 'pkg/go/**'
      - 'OpenFGAParser.g4'
      - 'OpenFGALexer.g4'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version-file: './pkg/go/go.mod'
        cache-dependency-path: './pkg/go/go.sum'
        check-latest: true

    - name: Build
      run: make all-tests-go

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    permissions:
      contents: write
      packages: write # publish a new github release
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: Roang-zero1/github-create-release-action@57eb9bdce7a964e48788b9e78b5ac766cb684803
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
