name: Test (Java)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  testCheckout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

  lint:
    name: Lint Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Set up JDK
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: 20
          distribution: "temurin"
          cache: gradle
          cache-dependency-path: |
            ./pkg/java/*.gradle*
            ./pkg/java/**/gradle-wrapper.properties

      - name: Lint Java source
        run: make lint-java

  check-gen:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Generate Antlr code and validate up to date
        run: |
            make antlr-gen-java
            git diff --text --exit-code ./pkg/java/src/main/gen
      

  test:
    name: Test Java
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ["11", "17", "20"]

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Set up JDK
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
          cache: gradle
          cache-dependency-path: |
            ./pkg/java/*.gradle*
            ./pkg/java/**/gradle-wrapper.properties

      - name: Test and Build with Gradle
        run: make test-java
