name: Test (JS)

on:
  workflow_call:

permissions:
  contents: read
    
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    
      - name: Set up node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./pkg/js/package-lock.json  
          
      - name: Audit dependencies
        run: make audit-js
    
      - name: Run eslint and prettier
        run: make lint-js

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      
      - name: Set up node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@openfga'
          always-auth: false
          cache: 'npm'
          cache-dependency-path: ./pkg/js/package-lock.json  
    
      - name: Build
        run: make all-tests-js
    