name: Test (JS)

on:
  workflow_call:

permissions:
  contents: read
    
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    
      - name: Set up node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./pkg/js/package-lock.json  
          
      - name: Audit dependencies
        run: make audit-js
    
      - name: Run eslint and prettier
        run: make lint-js

  check-gen:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

        - name: Generate Antlr code and validate up to date
          run: |
             make antlr-gen-js
             git diff --text --exit-code ./pkg/js/gen

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      
      - name: Set up node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@openfga'
          always-auth: false
          cache: 'npm'
          cache-dependency-path: ./pkg/js/package-lock.json  
    
      - name: Build
        run: make all-tests-js
    